name: Rainforest
on: [push]
jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: greet
        run: echo "Hola my frnd, github actions!"
        
  original-work:
    needs: [say-hello]
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v7

      - name: Install dependencies
        run: sudo apt install -y build-essential python3


      - name: Print working directory
        run: pwd

      - name: Run test
        run: python3 test.py 
